{% set name = "arraylake-client" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arraylake_client-{{ version }}.tar.gz
  sha256: 59e90957fd6beeb56b29f4411d51c47cb449fb5978333bb3c6fb260b2ca63218

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - arraylake = arraylake_client.cli.main:app

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<3.12
    - aiobotocore >=2.4,<3
    - zarr >=2.14,<=2.16
    - numpy >=1.20,<2
    - donfig >=0.7,<1.0
    - pydantic >=1.10,<2
    - httpx >=0.23,<1.0
    - cachetools >=5.3,<6
    - structlog >=23.1,<24
    - typing_extensions >=4,<5
    - email_validator >=2,<3
    - click >=8.1,<9
    - rich >=12.6,<14.0
    - typer >=0.6,<1.0
    - pyyaml >=6,<7.0
    - ruamel.yaml >=0.17,<1.0
    - python-dateutil >=2,<3
    - uvloop >=0.17,<1  # [unix]
    - aioitertools >=0.11,<1
  run_constrained:
    - fsspec >=2022.11.0
    - kerchunk >=0.1,<1.0
    - h5py >=3.7.0,<4.0.0
    - s3fs >=2022.11.0
    - ipytree >=0.2.2,<1.0

test:
  imports:
    - arraylake_client
  commands:
    # - pip check
    - arraylake --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://docs.earthmover.io
  summary: Python client for ArrayLake
  license: 'Unlicense'

extra:
  recipe-maintainers:
    - jhamman
    - rabernat
    - olimcc
    - dcherian
